### ISSUE TITLE
Code example typo in section 8.4.1

### ISSUE THREAD

**Issue by cgoutorbe** [cpq/bare-metal-programming-guide#14]
Hi first of all thanks for this awesome guide. 

I noticed what I think is a small typo in the code comment example.

In the readme.md: **section 8.4.1**
While setting port A3 to output mode.
the clearing is fine but then when setting only bit 6 to 1 the trailing comment is wrong. 

This is the current code example:

 ```
 * (volatile uint32_t *) (0x40020000 + 0) &= ~(3 << 6);  // CLear bits 6-7
 * (volatile uint32_t *) (0x40020000 + 0) |= 1 << 6;     // Set bits 6-7 to 1
```

What I think it should be:
```
  * (volatile uint32_t *) (0x40020000 + 0) &= ~(3 << 6);  // Clear bits 6-7
  * (volatile uint32_t *) (0x40020000 + 0) |= 1 << 6;     // Set bit 6 to 1
```

Not major, but fixing it might clear some confusion for newcomers. 

Thanks again,

**Comment by cpq** [comment]
@cgoutorbe thanks!
You're right that it is only 1 bit that gets set.
But in the guide, I am trying to say that the mode is specified by 2 bits. In the case of `A3` pin, bits 6 and 7. So we're setting the value of those 2 bits to 1.

**Comment by Sansveni** [comment]
I was confused by the same terminology.  I read it as saying both bits 6 and 7 are "1."  It confused me for quite a bit since I am rusty on using the & and | bitwise operators to set and clear bits.  Glad to see I was just misunderstanding the comment.  I agree with @cgoutorbe's suggestion.

Thank you for making this guide.  Coming from an electrical engineering background, I think this is just what I need to bridge the large gap in my understanding of microcontroller programming.

**Comment by cpq** [comment]
@Sansveni @cgoutorbe I do not agree with your proposal, to change the comment.
See, in many peripherals, there could be more complex value range.
For example, in the RCC controller, the value of the clock divider can range from 0 to 5. Example:

https://github.com/cpq/bare-metal-programming-guide/blob/9f5650178d9d0da50cdde71aba802f2fb9ffc1fc/step-6-clock/mcu.h#L120

There, PLL_M has value of 180, set in bits 6-14 (see datasheet 6.3.2 ).

So, the right way to say is that "we're setting bits X-Y to the value of Z". That's what the guide says, and it is correct in this regard.

I understand your confusion though, because in our particular case, we're setting two bits, 6-7, to the value of 1, which is actually sets only one bit. If that was a value of 3, that would set two bits. But we're setting to 1. Do you have any suggestion, as to how to rephrase the comment in a way that it still stays semantically correct, but would not trigger confusion?

**Comment by cpq** [comment]
@Sansveni @cgoutorbe I've added a detailed explanation for the bit operations - please let me know if that clears off a confusion you had.

**Comment by Sansveni** [comment]
@cpq I did end up figuring out the bit operations on my own, just barely.  I was just confused for a while because I thought when you said "set bits 6-7 to 1" that you mean "set bit 6 to 1 AND bit 7 to 1" and it made me question myself because I arrived at just bit 6 set to 1.  I think the explanation you added definitely helps clarify what the comment meant, thanks.  I realized you asked this before you added the detailed explanation, but in case you would still accept a suggestion, perhaps say "set bits X-Y to the decimal value of Z."

Also, I hope you don't mind me asking here, I went a little further in lesson 0 and I have a few questions:
`#define PIN(bank, num) ((((bank) - 'A') << 8) | (num))`
Does this work because 'A' is a char stored as its ASCII value, so 'B' - 'A' therefore equals 1, 'C' - 'A' = 2 to and so on?

`#define PINNO(pin) (pin & 255)`
This is to strip off (clear) the upper byte of pin, leaving just the lower byte, which is the pin number, correct?

`#define PINBANK(pin) (pin >> 8)`
By shifting pin to the right 8 times, you move the pinbank value from the upper byte to the lower byte and clear the upper byte, correct?

`gpio->MODER &= ~(3U << (n * 2));        // Clear existing setting`
Since the mode is represented by two bits, if you take the decimal 3, (binary 11 or 11b) and shift it by the pin number * 2, it will place 11b in the location for pin n on the mode register.  This value is then inverted before ANDing with the mode register so that you are only clearing those specific bits.

`gpio->MODER |= (mode & 3) << (n * 2);   // Set new mode`
This is just the reverse.  The only part I am not sure on is why `mode & 3` instead of just `mode`.  Is it just input validation to ensure mode is not greater than 3, since mode is of type uint8_t?  Or some other reason?

I almost did not ask these questions since they became obvious once I was able to put it to words.  However it would be nice to doublecheck my understanding.

**Comment by cpq** [comment]
@Sansveni Yes, what you said is correct!

```
 I thought when you said "set bits 6-7 to 1" that you mean "set bit 6 to 1 AND bit 7 to 1" and it made me question myself because I arrived at just bit 6 set to 1. 
```

Oh I see... I guess the right comment would be `Set bit range 6-7 to the decimal value of 1`

**Comment by cpq** [comment]
Closing this - let me know if it is still confusing!
